### PR TITLE
cljs-ajax, slimmed down

### PR DESCRIPTION
**Pull request by kloimhardt**
exposes to Scittle:

ajax.core/GET
ajax.core/POST
clojure.core/random-uuid
cljs.reader/read-string (-> renamed to) clojure.core/read-string
reagent.core/as-element

### CODE REVIEW

**Comment by borkdude** [comment]
@kloimhardt Looks good. `sci/copy-var` is only needed when you want to have a reified var in the environment so you can use `with-redefs`, `alter-var-root` etc on them, but it's not really important for scittle I think.

**Comment by borkdude** [comment]
@kloimhardt I now published an example:

https://borkdude.github.io/scittle/#cljs-ajax

**Comment by kloimhardt** [comment]
@borkdude ... aaand there is the combined babashka+scittle Guestbook web-app example. It is [here](https://github.com/kloimhardt/babashka-scittle-guestbook) and has only two files: an 80loc backend (based on your since long available template) and the file `guestbook-reagent/src/cljs/guestbook/core.cljs` from [Luminus](https://pragprog.com/titles/dswdcloj3/web-development-with-clojure-third-edition/).

I hope one day we will see this as the basis of a free-to-read opening chapter of some future edition of the book.

**Comment by borkdude** [comment]
@kloimhardt This is very exciting, thanks for making this. I will link it from the scittle page.

**Comment by borkdude** [comment]
I guess the cljs-ajax is kind of redundant now that all major browsers support the fetch API. That didn't occur to me a year ago.

**Comment by borkdude** [comment]
This is an example of the fetch API:

``` clojure
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/scittle@0.1.2/dist/scittle.js" type="application/javascript"></script>
    <script type="application/x-scittle">
      (defn handler [response]
        (js/alert (str response)))

      (defn make-request []
       (-> (js/fetch "index.html")
           (.then #(.text %))
           (.then #(js/alert %))))

      ;; export function to use from JavaScript:
      (set! (.-make_request js/window) make-request)
    </script>
  </head>
  <body>
    <button onclick="make_request()">
      Click me!
    </button>
  </body>
</html>
```

**Comment by kloimhardt** [comment]
Looking at your fetch example, it is obvious that removing clj-ajax from the Scittle canon is the way to go.

**Pull request merged**
